# Site settings
title: Nicola Malizia
email: me@nicolamalizia.me
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "https://nicolamalizia.me"

# Build settings
markdown: kramdown
permalink: pretty

# Add custom collections
collections:
  work:
    output: true

# Set defaults
defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"    
      author: "Stanley Stinson"
      date: ""
      title: ""
      category: ""
      tags: ""
      

theme: jekyll-theme-leap-day